services:
  app:
    image: wordpress:6.3.2-fpm
    volumes:
      - type: bind
        source: ./src/wp-content/
        target: /var/www/html/wp-content
      - wp-data:/var/www/html
    ports:
      - "${HOST_IP:-127.0.0.1}:9000:9000"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-db}
      WORDPRESS_DB_PORT: ${DB_PORT:-3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_USERNAME: ${DB_USERNAME:-admin}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-secret}
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:1.25.2
    ports:
      - "${HOST_IP:-127.0.0.1}:80:80"
    volumes:
      - type: bind
        source: ./src
        target: /workspace
      - wp-data:/var/www/html
    healthcheck:
      test: ['CMD', 'mysqladmin', 'plug', '-uroot', '-p${DB_ROOT_PASSWORD:-root}']
      interval: 5s
      timeout: 1s
      retries: 5
    depends_on:
      - app

  db:
    build:
      dockerfile: ./infra/db/Dockerfile
    ports:
      - "${HOST_IP:-127.0.0.1}:3306:3306"
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
      - ./infra/db/my.conf:/etc/mysql/conf.d/my.conf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-phper}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}

volumes:
  db-store:
  wp-data:
