volumes:
  db-store:

configs:
  db-config:
    file: ./db/my.cnf

services:
  app:
    build:
      context: .
      dockerfile: ./app/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_ENV=${APP_ENV:-local}
      - APP_URL=${APP_URL:-http://wordpress.local}
      - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - USER_UID=${HOST_UID}

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "${HOST_IP:-127.0.0.1}:80:80"
    volumes:
      - type: bind
        source: ./src
        target: /usr/share/nginx/html

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - "${HOST_IP:-127.0.0.1}:3306:3306"
    configs:
      - source: db-config
        target: /etc/my.cnf
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-phper}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}

