name: deploy-build-testing

on:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Version
        run: docker version

      - name: Docker Compose Settings
        run: echo APP_BUILD_TARGET=deploy > .env

      - name: Build Docker Images
        run: docker compose build app

      # - name: Run PHPUnit
      #   run: compose test
